[tool.poetry]
name = "task"
version = "0.1.0"
description = ""
authors = ["Author <author@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11, <3.13"
uvicorn = "^0.23.2"
httpx = "^0.25.0"
fastapi = "^0.115.6"
sqlalchemy = "^2.0.37"
aiosqlite = "^0.20.0"
pre-commit = "^4.6.0"
pydantic-settings = "^2.14.1"
asyncpg = "^0.31.0"
loguru = "^0.7.3"
aiokafka = "^0.14.0"
orjson = "^3.11.9"
redis = "^8.0.0"
avro = "^1.12.1"
pytest = "^9.1.1"
pytest-asyncio = "^1.4.0"
faker = "^40.23.0"


[tool.poetry.group.dev.dependencies]
pylint = "^4.0.6"
pylint-pydantic = "^0.4.1"
pytest-alembic = "^0.12.1"
pytest-cov = "^7.1.0"
pytest-env = "^1.6.0"
pytest-mock = "^3.15.1"
pytest-mock-server = "^0.3.0"
pytest-xdist = "^3.8.0"
ruff = "^0.15.18"
mypy = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
    "I",
    "E",
    "W",
    "F"
    ]

[tool.ruff.format]
quote-style = 'single'
indent-style = 'space'

[tool.mypy]
plugins = [
    "pydantic.mypy"
]
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode= "auto"
